# Generated by Django 3.2.8 on 2021-10-27 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
        ('produtos', '0003_auto_20211024_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdCores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProdTamanhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproduto1', models.IntegerField(default=0)),
                ('idproduto2', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='PC',
            new_name='ProdCategorias',
        ),
        migrations.RemoveField(
            model_name='cores',
            name='idproduto',
        ),
        migrations.RemoveField(
            model_name='tamanhos',
            name='idproduto',
        ),
        migrations.RenameModel(
            old_name='Desconto',
            new_name='Descontos',
        ),
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produtos',
        ),
        migrations.DeleteModel(
            name='ProdutoRelacionado',
        ),
        migrations.AddField(
            model_name='relacaoprodutos',
            name='iddesconto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.descontos'),
        ),
        migrations.AddField(
            model_name='prodtamanhos',
            name='idproduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
        migrations.AddField(
            model_name='prodtamanhos',
            name='idtamanhos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tamanhos'),
        ),
        migrations.AddField(
            model_name='prodcores',
            name='idcores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.cores'),
        ),
        migrations.AddField(
            model_name='prodcores',
            name='idproduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
    ]
