# Generated by Django 3.2.8 on 2021-10-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
        ('produtos', '0004_auto_20211027_0452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Cores',
            new_name='Cor',
        ),
        migrations.RenameModel(
            old_name='Descontos',
            new_name='Desconto',
        ),
        migrations.RenameModel(
            old_name='ProdCategorias',
            new_name='ProdCategoria',
        ),
        migrations.RenameModel(
            old_name='ProdCores',
            new_name='ProdCor',
        ),
        migrations.RenameModel(
            old_name='ProdTamanhos',
            new_name='ProdTamanho',
        ),
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
        migrations.RenameModel(
            old_name='RelacaoProdutos',
            new_name='RelacaoProduto',
        ),
        migrations.RenameModel(
            old_name='Tamanhos',
            new_name='Tamanho',
        ),
    ]
