# Generated by Django 3.2.8 on 2021-10-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('pagamento', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_total', models.FloatField(max_length=100)),
                ('d_total', models.FloatField(max_length=100)),
                ('v_final', models.FloatField(max_length=100)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('idpagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamento.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido')),
                ('idproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='CP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcarrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.carrinho')),
                ('idproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
