# Generated by Django 3.2.8 on 2021-10-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20211027_0459'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CP',
            new_name='ProdCarrinho',
        ),
        migrations.RenameModel(
            old_name='PP',
            new_name='ProdPedido',
        ),
    ]
