# Generated by Django 3.2.8 on 2021-10-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        ('pagamento', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='idcarrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.carrinho'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='idcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
